credentials:
  usernames:
    admin:
      email: admin@example.com
      name: Admin
      password: "$2b$12$Vp2IQWQG7M4OZknLZEu/Ceq9dPgDx3bw6hZ6zMzQ8a8/5slFOZhcu"  # password123
    demo:
      email: demo@example.com
      name: Demo User
      password: "$2b$12$VP9gzGcUgj1HwNTfHzPYjOZ4cAKRPLlvK7lSvRb93HqHTDN9/XyJW"  # demo456
